### ISSUE TITLE
Binary naming

### ISSUE THREAD

**Issue by Wondertan** [proximax-storage/sirius-storage-testnet-onboarding#4]
I am concerned about naming and to be honest, I don't like them currently. 

- `drive` instead of `dfms`. DFMS is more abstract than just Drive. Furthermore, Drive from DFMS perspective is only a part of DFMS which has an unlimited amount of Drives, e.g. when we Compose a new Contract using `dfms` we are creating new Drive in the network with the Contract between network participant about the Drive. That is, any client my create may create multiple Drives and access them through `dfms` or even access Drives created by other users, cause they are public by default. 

- `replicator` instead of `dfmsr`. The `replicator` is not self-explanatory. From the name, we can get only that it replicates something, but what?  `dfmsr` on the other side add additional `r` to abbreviation which also represents `replicator`, but we can also get that it replicates something regarding DFMS.  In addition, both `dfms` and `dfmsr` follows UNIX like style.

/cc @alvin-reyes @shinneng

**Comment by carlocayos** [comment]
If I remember it correctly, the marketing team dropped DFMS and replaced it with **Sirius Storage**. 
- We should drop DFMS
- The names `drive` and `replicator` sounds too generic. Maybe add a prefix `sirius_drive` and `sirius_replicator`?

**Comment by carlocayos** [comment]
From Alvin:

> Sirius Storage is the platform name.
> dfms is code/tech name of the drive / client.
> dfmsr is the code/tech name of the replicator/verifier.

**Comment by carlocayos** [comment]
Docker hub repos to match.
https://hub.docker.com/r/proximax/sirius-storage-dfmsr
https://hub.docker.com/r/proximax/sirius-storage-dfms
